<a href="https://colab.research.google.com/github/sujoygiri/portfolio/blob/master/DiabetesPrediciton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
# importing all required dependency
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [33]:
# loading diabetes dataset csv file
disabetes_dataset = pd.read_csv('/content/diabetes (1).csv')

In [34]:
# fetching top 5 row of csv dataset
disabetes_dataset.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             72             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3       89             66             23       94  28.1   
4      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [35]:
disabetes_dataset.shape

(768, 8)

In [36]:
disabetes_dataset.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   120.894531      69.105469      20.536458   79.799479   31.992578   
std     31.972618      19.355807      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    140.250000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.240885    0.348958  
std                    0.331329   11.760232    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [37]:
disabetes_dataset['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [38]:
X = disabetes_dataset.drop(columns='Outcome',axis=1)
Y = disabetes_dataset['Outcome']

In [39]:
X.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             72             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3       89             66             23       94  28.1   
4      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [40]:
# scaler = StandardScaler()

In [41]:
# standaraized_data = scaler.fit_transform(X)

In [42]:
# standaraized_data

In [43]:
# X = standaraized_data
# Y = disabetes_dataset['Outcome']

In [69]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2,stratify=Y,random_state=2)
print(X_train.values)
print(Y_train)

[[1.19e+02 0.00e+00 0.00e+00 ... 3.24e+01 1.41e-01 2.40e+01]
 [1.05e+02 7.00e+01 3.20e+01 ... 3.08e+01 1.22e-01 3.70e+01]
 [1.89e+02 6.00e+01 2.30e+01 ... 3.01e+01 3.98e-01 5.90e+01]
 ...
 [8.50e+01 7.40e+01 0.00e+00 ... 3.01e+01 3.00e-01 3.50e+01]
 [1.12e+02 7.80e+01 4.00e+01 ... 3.94e+01 2.36e-01 3.80e+01]
 [8.60e+01 6.80e+01 3.20e+01 ... 3.58e+01 2.38e-01 2.50e+01]]
619    1
329    0
13     1
476    1
45     1
      ..
303    1
592    1
559    0
725    0
253    0
Name: Outcome, Length: 614, dtype: int64


In [74]:
classifier = svm.SVC(kernel='linear')

In [75]:
classifier.fit(X_train.values,Y_train)

SVC(kernel='linear')

In [76]:
X_train_prediction = classifier.predict(X_train.values)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print(training_data_accuracy)

0.7882736156351792


In [77]:
X_test_prediction = classifier.predict(X_test.values)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(test_data_accuracy)

0.7662337662337663


In [78]:
input_data = np.asarray((103,108,37,0,39.2,0.305,65))
print(input_data)
reshaped_input_data = input_data.reshape(1,-1)
print(reshaped_input_data)
# std_input_data = scaler.transform(reshaped_input_data)
# print(std_input_data)
# prediction = classifier.predict(std_input_data)

prediction = classifier.predict(reshaped_input_data)
print(prediction)

[103.    108.     37.      0.     39.2     0.305  65.   ]
[[103.    108.     37.      0.     39.2     0.305  65.   ]]
[0]


In [79]:
import joblib

In [80]:
joblib.dump(classifier,'Diabetes_prediction_ml_model.cls')

['Diabetes_prediction_ml_model.cls']

In [81]:
model = joblib.load("/content/Diabetes_prediction_ml_model.cls")

In [82]:
user_data = np.asarray((140,82,43,325,39.2,0.528,58))
reshaped_user_data = user_data.reshape(1,-1)
model.predict(reshaped_user_data)

array([1])